//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMaster
    {
        public int CompID { get; set; }
        public string Name { get; set; }
        public string LegalName { get; set; }
        public string ACType { get; set; }
        public string Industry { get; set; }
        public string Description { get; set; }
        public string Phone { get; set; }
        public string AltPhone { get; set; }
        public string Fax { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Website { get; set; }
        public string BStreet { get; set; }
        public string BCity { get; set; }
        public string BState { get; set; }
        public string BPostCode { get; set; }
        public string BCountry { get; set; }
        public string SStreet { get; set; }
        public string SCity { get; set; }
        public string SState { get; set; }
        public string SPostCode { get; set; }
        public string SCountry { get; set; }
        public string ContactPerson { get; set; }
        public string ABN { get; set; }
        public string BHour { get; set; }
        public string ServiceStatus { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
