//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class techflowEntities : DbContext
    {
        public techflowEntities()
            : base("name=techflowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CompanyMaster> CompanyMasters { get; set; }
        public DbSet<TicketMaster> TicketMasters { get; set; }
        public DbSet<TicketStatusMaster> TicketStatusMasters { get; set; }
        public DbSet<TicketTran> TicketTrans { get; set; }
        public DbSet<UserLog> UserLogs { get; set; }
        public DbSet<UserMaster> UserMasters { get; set; }
        public DbSet<TicketSubType> TicketSubTypes { get; set; }
        public DbSet<TicketTypeMaster> TicketTypeMasters { get; set; }
    


    }
}
