//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSubType
    {
        public int TTSID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string SubType { get; set; }
        public string SubDesc { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
