//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketMaster
    {
        public int TicketID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SenderEmail { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public Nullable<int> TicketStatusID { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> SubType { get; set; }
    }
}
