//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int UID { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> Role { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> ReqQ { get; set; }
        public Nullable<bool> Power { get; set; }
        public Nullable<bool> Access { get; set; }
        public Nullable<bool> Tickets { get; set; }
        public Nullable<bool> Portal { get; set; }
        public Nullable<bool> Invoice { get; set; }
        public Nullable<decimal> mobile { get; set; }
    }
}
